name: Deploy API to Server

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to deploy"
        required: true
        default: "main"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to DEV Server
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ${{ secrets.SERVER_DEPLOYMENT_PATH }}

            # Clone repo if missing
            if [ ! -d ".git" ]; then
              git clone https://github.com/zoltanpal/api.palzoltan.net.git .
              git checkout ${{ github.ref_name }}
            fi

            # Fetch latest changes
            git fetch origin

            # Hard reset to match the latest remote state
            git reset --hard origin/${{ github.ref_name }}
            git clean -fd  # Remove untracked files

            git checkout ${{ github.ref_name }}

            # Set up Python & Poetry
            export POETRY_HOME=$HOME/.poetry
            export PATH="$POETRY_HOME/bin:$HOME/.local/bin:$PATH"

            if ! command -v poetry &> /dev/null; then
              curl -sSL https://install.python-poetry.org | python3 -
              export PATH="$HOME/.local/bin:$PATH"
            fi

            # Ensure poetry uses in-project venv
            poetry config virtualenvs.in-project true

            # Install dependencies
            poetry install --no-root
