name: Deploy to Server

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to DEV Server
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ${{ secrets.SERVER_DEPLOYMENT_PATH }}
            if [ ! -d ".git" ]; then
              git clone https://github.com/zoltanpal/api.palzoltan.net.git .
            fi
  
            # Fetch the latest changes
            git fetch origin
  
            # Force reset the local branch to match the remote branch
            git checkout ${{ github.ref_name }}
            git reset --hard origin/${{ github.ref_name }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org | python3 -

      - name: Poetry config
        run: poetry config virtualenvs.in-project true

      - name: Install dependencies
        run: poetry install

      - name: Update dependencies
        run: poetry update
            
            
