name: Deploy API

on:
  push:
    branches:
      - feature/refactoring

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to DEV Server
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ${{ secrets.SERVER_DEPLOYMENT_PATH }}

            # Clone repo if missing
            if [ ! -d ".git" ]; then
              git clone https://github.com/zoltanpal/api.palzoltan.net.git .
              git checkout ${{ github.ref_name }}
            else
              git fetch origin
              git checkout ${{ github.ref_name }}
              git pull --rebase origin ${{ github.ref_name }}
            fi

            # Set up Python & Poetry
            export POETRY_HOME=$HOME/.poetry
            export PATH="$POETRY_HOME/bin:$PATH"

            if ! command -v poetry &> /dev/null; then
              curl -sSL https://install.python-poetry.org | python3 -
              export PATH="$HOME/.local/bin:$PATH"
            fi

            # Ensure poetry uses in-project venv
            poetry config virtualenvs.in-project true

            # Install dependencies
            poetry install --no-root

            # Update dependencies only if needed
            poetry update
